
#SIGNUP
POST {{$dotenv BASEURL}}/auth/signup
Content-Type: application/json

# {
#     "password": "hello",
#     "email": "test@gmail.com",
#     "username": "test"
# }
{
    "password": "hello",
    "email": "test2@gmail.com",
    "username": "test2"
}

###
#LOGIN
POST {{$dotenv BASEURL}}/auth/login
Content-Type: application/json

{
    "password": "hello",
    "usernameOrEmail": "test2@gmail.com"
}

###
# GET TOKEN
GET {{$dotenv BASEURL}}/auth/token
###
#logout
GET {{$dotenv BASEURL}}/auth/logout

###
# @Get user

GET {{$dotenv BASEURL}}/auth/user
Authorization: bearer {{$dotenv ACCESSTOKEN}}