@pid = 62594be092fed4c56bc2d4b4
@cid = 624f0b161dd4f5f0b1918de6
###
# @create a comment
POST {{$dotenv BASEURL}}/api/posts/{{pid}}/comments
Authorization: bearer {{$dotenv ACCESSTOKEN}}
Content-Type: application/json

{
    "text": "Hello i love u3"
}

###
# get all comments of a post
GET {{$dotenv BASEURL}}/api/posts/{{pid}}/comments

###
# get single comment
GET {{$dotenv BASEURL}}/api/posts/{{pid}}/comments/{{cid}}

###
# update a comment
PUT {{$dotenv BASEURL}}/api/posts/{{pid}}/comments/{{cid}}
Authorization: bearer {{$dotenv ACCESSTOKEN}}
Content-Type: application/json

{
    "text": "I change my mind sir"
}
### delete a comment
DELETE {{$dotenv BASEURL}}/api/posts/624f0b051dd4f5f0b1918de1/comments/{{cid}}
Authorization: bearer {{$dotenv ACCESSTOKEN}}