@pid = 624d9f0cdd38d5a28188cea4
###
# create a post
POST {{$dotenv BASEURL}}/posts/
Authorization: bearer {{$dotenv ACCESSTOKEN}}
Content-Type: application/json

{
    "text": "This is my asdas post bruh2"
}

###
# get all posts
GET {{$dotenv BASEURL}}posts/

###
# get single posts
GET {{$dotenv BASEURL}}posts/{{pid}}

###
# update a post
PUT {{$dotenv BASEURL}}posts/{{pid}}
Authorization: bearer {{$dotenv ACCESSTOKEN}}
Content-Type: application/json

{
    "text": "This is my 2 asdasda post updated by test2"
}
### delete a post
DELETE {{$dotenv BASEURL}}posts/{{pid}}
Authorization: bearer {{$dotenv ACCESSTOKEN}}