#SIGNUP
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "password": "hello",
    "email": "test@gmail.com",
    "username": "test"
}

###
#LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "password": "hello",
    "usernameOrEmail": "test@gmail.com"
}

###
# GET TOKEN
GET http://localhost:3000/api/auth/token
###
#logout
GET http://localhost:3000/api/auth/logout

###
# create a post
POST http://localhost:3000/api/posts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQ5NzM2ODE3ZTQ1OTM4NTkzMDExZCIsInVzZXJuYW1lIjoidGVzdCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjQ5MjUyNzA2LCJleHAiOjE2NDkyNTI3MTZ9._lgnW_-PBwfq1SRG0aVj0gqOgPKhuYQrKdFUnrx34AM
Content-Type: application/json

{
    "text": "This is my first post"
}

